typography_spectrum: 0.3932036096230149
color:
  brandStrength: 0.19356627785600722
  lightness: 0.954221777850762
  saturation: 0.43022329173982143
  rhythmicContrast: 0.15721021289937198
  brandColors:
    - '#121218'
    - '#98978D'
    - '#282826'
    - '#6F695D'
    - '#424545'
layout_spectrum: 0.019368130713701248
name: hustler
navigation:
  - name: Hustler Home
    url: 'http://hustler.global'
    type: external
  - name: Flight plan
    id: 4b28447e-3b3f-4a1b-9611-8f306f2acbc9
    type: content
  - name: Get in Touch
    url: 'mailto:hello@hustler.global'
    type: external
title: Do The Hustler
description: A Bustling Aggregator for Go-Getters
